// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyaIac3SDRbSMCTd9WuEjMrz0gX-8wGY4',
    appId: '1:595650006865:android:ec02c266cc121fac2e0d70',
    messagingSenderId: '595650006865',
    projectId: 'sales-75413',
    storageBucket: 'sales-75413.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLMR5ctmn6WEM54snbnP8mOsvSz87jiCM',
    appId: '1:595650006865:web:af766b2af64027bd2e0d70',
    messagingSenderId: '595650006865',
    projectId: 'sales-75413',
    authDomain: 'sales-75413.firebaseapp.com',
    storageBucket: 'sales-75413.firebasestorage.app',
    measurementId: 'G-JFEGBSSNZT',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLMR5ctmn6WEM54snbnP8mOsvSz87jiCM',
    appId: '1:595650006865:web:6ba375b20a4b82cb2e0d70',
    messagingSenderId: '595650006865',
    projectId: 'sales-75413',
    authDomain: 'sales-75413.firebaseapp.com',
    storageBucket: 'sales-75413.firebasestorage.app',
    measurementId: 'G-8TF30QJPKT',
  );

}